### PR TITLE
fix: UI: Correct useEffect() re-rendering during file import.

### PR DESCRIPTION
**Pull request by pleacu**
Fixes: #3781

@igarashitm - please try your import with this change.  I could not reproduce your situation but corrected useEffect rerendering triggering which should catch your issue.

### CODE REVIEW

**Comment by igarashitm** [comment]
Seems it contains a leftover from dependabot PRs in yarn.lock, let me clean it up first.

**Comment by igarashitm** [comment]
Nope it doesn't work - even reload didn't help this time.

**Comment by igarashitm** [comment]
Hmm, it's inconsistent... after it reproduced, I closed the browser tab, restarted the stasndalone with `mvn clean spring-boot:run`, then opened a new tab, then it worked. Then yet again, I closed the browser tab, restarted the standalone, opened a new tab, then the issue reproduced again.

**Comment by pleacu** [comment]
Will close this PR for now since it seems to have no effect (but does appear to be more efficient).  I went to my local `atlasmap/standalone` and `mvn clean spring-boot:run` followed by `http://localhost:8585/` in a separate browser window in various sequences and can not get the schema source to fail to load (still using the fix here).  I also tried the fully standalone `java -jar ~/git-clone/atlasmap/standalone/target/atlasmap-standalone.jar` as well as the standard storybook atlasmap instance - also unable to get it to fail for me.  Perhaps a browser instance issue? `Version 90.0.4430.212 (Official Build) (64-bit)`

**Pull request closed without merging**
