### PR TITLE
fix: support multiplicity transformation delimiter pulldown and updat…

### PR DESCRIPTION
**Pull request by pleacu**
…e css styling

Fixes: #1766

sc1

### CODE REVIEW

**Comment by riccardo-forina** [comment]
Uhm, I feel like we could benefit from some pointers from @atlasmap/uxd

**Comment by pleacu** [comment]
Here's a similar capture of the angular UI:
sc2

@dongniwang - wdyt?

**Comment by pleacu** [comment]
Updated to remove the lightgray background color:
sc3

**Comment by dongniwang** [comment]
Hey @riccardo-forina and @pleacu - thanks for tagging me. 

Are we talking about the delimiter dropdown? I'm a little bit confused about the relationship between the dropdown and the content beneath it. What does the interaction look like?

**Comment by pleacu** [comment]
The dropdown is a standard dropdown menu.  I think the main area of
contention was  the use of a lightgray background to help distinguish the
sources mapping fields from the target mapping fields.

**Pull request merged**
