### PR TITLE
fix: Moved release profiles into root pom and added release targets to build.sh

### PR DESCRIPTION
**Pull request by igarashitm**
Relates to: #126

### CODE REVIEW

**Comment by igarashitm** [comment]
Hi @rhuss , @iocanel ,
I added `release.sh` to perform `mvn release:prepare release:perform`, and moved release related profiles into root POM. Mainly because I thought release should run only if `build.sh` successfully complete. So we can run `build.sh` to build and then `release.sh` for release from Jenkins. WDYT?

@cunningt ,
I'm also wondering if this change affects product build or not (GitHub wisely suggested you as a reviewer :-). Can you take a look?

**Comment by rhuss** [comment]
> I added release.sh to perform mvn release:prepare release:perform, and moved release related profiles into root POM. Mainly because I thought release should run only if build.sh successfully complete. So we can run build.sh to build and then release.sh for release from Jenkins. WDYT?

Normally a release _includes_ a full build, so I actually would not separate them (as it also probably shares common functionality). Maybe adding an option to build.sh to enable the profile and then call the proper mvn targets ?

**Comment by igarashitm** [comment]
@rhuss thanks for the comment, OK that works for me.
I added `--release-version` and `--development-version` into build.sh, and if `--release-version` is specified, it invokes `release:prepare release:perform release:clean` targets at last.

**Comment by igarashitm** [comment]
Alright, @iocanel is this enough to get you work on adding Jenkins job for AtlasMap release?

**Pull request merged**
