### PR TITLE
fix: Mapping preview - when the input is deleted, the result field isn' cleaned too

### LINKED ISSUE #2360: Mapping preview - when the input is deleted, the result field isn' cleaned too
Related to [ENTESB-14014](https://issues.redhat.com/browse/ENTESB-14014)

### PR DESCRIPTION
**Pull request by jpav**
Fixes #2360

### CODE REVIEW

**Review by pleacu — APPROVED** [review]
+1

**Comment by igarashitm** [comment]
@jpav is this community only? doesn't it need backport to 2.0.x branch?

**Comment by jpav** [comment]
Yes, it needs to be backported. I was waiting for the corresponding production ticket to be reviewed and accepted, but I can do it now if you'd like.

**Comment by igarashitm** [comment]
I'm not sure about production ticket other than ENTESB-14014, but as I said I'm making a final 2.0.x release before code freeze today.

**Comment by gashcrumb** [comment]
@jpav if an issue is marked to be included in a product release you can just backport the fix to the relevant fix branch.

**Comment by igarashitm** [comment]
I did it so that I can start the release

**Pull request merged**
