### PR TITLE
fix: Add expression box support for adding field nodes.

### PR DESCRIPTION
**Pull request by pleacu**
Fixes: #1914

Ran into an issue with the newest server.  Works with older server - will address server issue separately.

Still needs d&d support as well as keyboard nav (arrows, tab)

### CODE REVIEW

**Comment by riccardo-forina** [comment]
It doesn't seem to be working for me? If I select a mapping the fx input is always empty, if I write @ and pick a field the input remains empty.

**Comment by pleacu** [comment]
Hey @riccardo-forina  -  checked again on my end - seems to be okay.  Are you running into any of your changes with it?  Should just be master with my PR.

**Comment by riccardo-forina** [comment]
No I simply clicked on the netlify preview link up above

**Comment by pleacu** [comment]
@riccardo-forina - strange - it looks like netlify doesn't like something - the 'reset all' button also doesn't work for instance.

**Comment by pleacu** [comment]
I think I found the netlify issue - strange it doesn't manifest itself outside of netlify...

**Comment by pleacu** [comment]
@riccardo-forina - https://deploy-preview-1944--atlasmap.netlify.app/atlasmap-core/?path=/story/atlasmap--standalone works now.

**Pull request merged**
