### PR TITLE
[ENTESB-20837] Remove references to org.slfj4:slf4j-log4j12

### PR DESCRIPTION
**Pull request by grgrzybek**
Fixes: #

### CODE REVIEW

**Review by igarashitm — APPROVED** [review]
Thanks @grgrzybek :+1:

**Comment by grgrzybek** [comment]
ubuntu-latest/java11 failed with:
```
Error:  NullPointerException
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error: Process completed with exit code 1.
```

no idea...

**Comment by grgrzybek** [comment]
anyway, I think it can be merged. What should I do?

**Comment by igarashitm** [comment]
Hmm NPE when generating javadoc, strange... I'll take a look

**Comment by grgrzybek** [comment]
thanks @igarashitm !

**Pull request merged**
