### PR TITLE
fix: Update Java, Xml and Json modules to not create validations for …

### PR DESCRIPTION
**Pull request by sunilmeddr**
…core field types

Fixes: #14

### CODE REVIEW

**Comment by rohanmars** [comment]
@sunilmeddr can you describe exactly what you mean by "do not create validations for core types"? Any by core types, specifically which types do you mean?

**Comment by sunilmeddr** [comment]
@rohanmars   JavaModule, XmlModule, and JsonModule validations should not throw an error if they detect a 'core *Field', such as: ConstantField, PropertyField, LookupField, etc

**Comment by rohanmars** [comment]
This PR says "do not create validations for core field types". Does "if (getFieldType().isAssignableFrom(field.getClass()))" exclude core field types from validation?

**Comment by sunilmeddr** [comment]
Yes

On Jan 8, 2018 3:04 PM, "Rohan Mars" <notifications@github.com> wrote:

This PR says "do not create validations for core field types". Does "if
(getFieldType().isAssignableFrom(field.getClass()))" exclude core field
types from validation?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/atlasmap/atlasmap/pull/213#issuecomment-356079989>, or mute
the thread

**Comment by rohanmars** [comment]
LGTM :+1:

**Pull request merged**
