### PR TITLE
fix: Corrected line machine support to handle added field mappings fr…

### PR DESCRIPTION
**Pull request by pleacu**
…om no document/ panel sources.

Fixes: #1442

### CODE REVIEW

**Comment by igarashitm** [comment]
Could line-machine subscribe `mappingUpdated$` instead?
https://github.com/atlasmap/atlasmap/pull/1443/files#diff-33a65a8e6d54bd6716a9670a71fe3408L46
In this way individual components no longer have to explicitly emit mapping updated event. I think `mappingUpdatedSource` notified via `notifyMappingUpdated()` is already a centralized mapping updated event source.

**Comment by pleacu** [comment]
> Could line-machine subscribe `mappingUpdated$` instead?
> https://github.com/atlasmap/atlasmap/pull/1443/files#diff-33a65a8e6d54bd6716a9670a71fe3408L46
> In this way individual components no longer have to explicitly emit mapping updated event. I think `mappingUpdatedSource` notified via `notifyMappingUpdated()` is already a centralized mapping updated event source.

Actually yes - I think I can get rid of the AdmRedrawMappingLinesEvent entirely.  The real issue is that validateMappings() fails every once in a while with:
`
javax.ws.rs.WebApplicationException: HTTP 400 Bad Request
	at io.atlasmap.service.AtlasService.fromJson(AtlasService.java:790) ~[atlas-service-1.43.0-SNAPSHOT.jar:1.43.0-SNAPSHOT]
	at io.atlasmap.service.AtlasService.validateMappingRequest(AtlasService.java:439) ~[atlas-service-1.43.0-SNAPSHOT.jar:1.43.0-SNAPSHOT]
`

It passes the next time through.  The UI trace dump looks good.  The problem is that when it fails notifyMappingUpdated() ends up not invoking this.mappingUpdatedSource.next() as it should 
https://github.com/atlasmap/atlasmap/blob/master/ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts#L661-L663

We trap the error as just a warning in the log.

**Comment by pleacu** [comment]
Hey @igarashitm - there are two different line-machine based events that are being subscribed to.  One associates a line update with a mapping update (mappingUpdatedSource mappingUpdatedSubscription mappingUpdated$) the other associates a line update event with anything else (scroll, search box, etc).  It didn't seem correct to trigger a mapping update line event on a scroll so this latest PR preserves the two.  If we need to distinguish them later we can.

**Comment by igarashitm** [comment]
Ah OK. Then I would create a separate line refresh event source in the mapping-management.service and add `notifyLineRefresh()`. Then `notifyMappingUpdated()` would invoke `notifyLineRefresh()` as well. line-machine.component just subscribe line refresh event source instead of mapping updated. In this way document-definition.component and line-machine.component no longer have to be tightly coupled, reducing bug source around the complicated line refresh events.

**Comment by pleacu** [comment]
new commit coming...

**Pull request closed without merging**
