### PR TITLE
Replace tsdx for atlasmap, core & standalone

### PR DESCRIPTION
**Pull request by kahboom**
## Description
Fixes: #3359 

Tasks:
- Remove tsdx
- Use Webpack 4.x instead, with the goal of upgrading to 5.x in the near future

## Comments
I've tested `yarn build`, `yarn lint`, `yarn start`, and `yarn test` for `atlasmap`, `atlasmap-core`, and `atlasmap-standalone`, and they work fine, however, there are two warnings in production mode, or with `yarn build`:

```bash
console.warn ../../node_modules/mobx-react-lite/batchingForReactDom.js:2
      [mobx-react-lite] importing batchingForReactDom is no longer needed
```

^ This warning existed already before, but was suppressed by tsdx. It should go away once we begin to upgrade more deps, like `@patternfly/react-topology`.

And the second one is about the asset size limit, which is something we are having in Kaoto as well. I can fix this with a subsequent PR, but if you find it's urgent then let me know @igarashitm @pleacu .

```bash
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  app.js (5 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (5 MiB)
      app.js
```

## Screenshots
Some screenshots to show it didn't explode..

Screen Shot 2022-05-05 at 4 23 42 pm

Screen Shot 2022-05-05 at 4 25 56 pm

Screen Shot 2022-05-05 at 4 25 44 pm

### CODE REVIEW

**Review by igarashitm — APPROVED** [review]
LGTM! can you squash the commits and put the commit message like following?
https://github.com/atlasmap/atlasmap/wiki/AtlasMap-Developer-Memo#commit-message

**Comment by kahboom** [comment]
sure @igarashitm will do, thanks! is there any reason why the builds are failing for both PRs? but particularly for this one

**Comment by igarashitm** [comment]
Putting aside the windows builds failing anyway (#3145) - 
https://github.com/atlasmap/atlasmap/runs/6309049974?check_suite_focus=true
> [INFO] @atlasmap/atlasmap: ERROR in ./src/UI/ExpressionContent.tsx
> [INFO] @atlasmap/atlasmap: Module not found: Error: Can't resolve '@atlasmap/core' in '/home/runner/work/atlasmap/atlasmap/ui/packages/atlasmap/src/UI'
so it shouds like the `@atlasmap/atlasmap` build can't see the build outcome from `@atlasmap/core` build. I'm not sure why this fails while it's fine with tsdx build, I'll take a look

**Comment by igarashitm** [comment]
hmm my local build just succeeded, will try to build from a freshly cloned repo, after I fix #3992

**Comment by igarashitm** [comment]
OK the build error reproduced locally with freshly cloned repo
```
@atlasmap/atlasmap: ERROR in ./src/UI/MappingTransformation.tsx
@atlasmap/atlasmap: Module not found: Error: Can't resolve '@atlasmap/core' in '/home/tomo/workspace/iPaaS/atlasmap/tmp/rachel/ui/packages/atlasmap/src/UI'
@atlasmap/atlasmap:  @ ./src/UI/MappingTransformation.tsx 18:0-43 104:17-26
@atlasmap/atlasmap:  @ ./src/UI/index.ts
@atlasmap/atlasmap:  @ ./src/index.ts
@atlasmap/atlasmap: ERROR in ./src/UI/ExpressionContent.tsx
@atlasmap/atlasmap: Module not found: Error: Can't resolve '@atlasmap/core' in '/home/tomo/workspace/iPaaS/atlasmap/tmp/rachel/ui/packages/atlasmap/src/UI'
@atlasmap/atlasmap:  @ ./src/UI/ExpressionContent.tsx 23:0-52 185:33-51 226:22-40 359:49-67
@atlasmap/atlasmap:  @ ./src/UI/index.ts
@atlasmap/atlasmap:  @ ./src/index.ts
```
I think it succeeds only when the old build artifacts are left in the `ui/packages/atlasmap-core/dist`. I did `rm -rf packages/atlasmap-core/dist; yarn build` and the build error reproduced even in the old local repo.

**Comment by kahboom** [comment]
Closing until resolving issue with `core`

**Pull request closed without merging**
