### PR TITLE
fix: Multiple properties with same name allowed

### LINKED ISSUE #2336: Multiple properties with same name allowed
Related to [ENTESB-14388](https://issues.redhat.com/browse/ENTESB-14388)

### PR DESCRIPTION
**Pull request by jpav**
Fixes #2336 

I found the same issue with constants, so I fixed that here also.

### CODE REVIEW

**Comment by pleacu** [comment]
Need a small tweek.  You need to compare a duple for properties - name/scope.  Ref:
https://issues.redhat.com/browse/ENTESB-14388?focusedCommentId=14423256&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14423256

**Comment by jpav** [comment]
Argh, Tomo told me this up front, and I totally forgot. Thanks, Paul, I'll fix that.

**Comment by jpav** [comment]
@pleacu I've made that change, plus realized my first solution violated the UI dependency hierarchy of AtlasMap vs. Views vs. UI.

**Review by pleacu — APPROVED** [review]
+1
There does exist an issue where editing the first property causes you to edit the second property but it doesn't appear to be related to this fix.  I'll create an issue for it.

**Pull request merged**
