### PR TITLE
fix: Disable the conditional expression box when selecting a differen…

### PR DESCRIPTION
**Pull request by pleacu**
…t mapping.

Fixes: #961

### CODE REVIEW

**Comment by igarashitm** [comment]
Doesn't this disable expression if select other mapping and get back? Let's say mapping-a has expression and mapping-b without expression and mapping-a is activated. Once you select mapping-b and then select mapping-a, expression for mapping-a is going to be disabled?

**Comment by pleacu** [comment]
The expression for mapping-A is retained, you just need to select the f(x) icon to see it.  The issue I was seeing is that the conditional expression for mapping-B was being shown when selecting mapping-A if both were enabled.  By disabling the cond expr box by default if the user establishes a new active mapping and then returns to an older one they have to reclick the f(x) icon

**Comment by igarashitm** [comment]
But once enableExpression is set to `false`, expression is disabled and `Concatenate` is used:
https://github.com/atlasmap/atlasmap/blob/master/ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts#L93

So I think instead we need to refresh the expression when mapping is selected.

**Comment by igarashitm** [comment]
This is weird though, FieldMappingPair.transition.expression should have corresponding Expression object for each mapping. ExpressionComponent might need to subscribe mapping selection event.

**Comment by pleacu** [comment]
True - I thought the simplest way to refresh was to trigger through the transition html by toggling off the enableExpression.  If a user enables the cond expression box are they enabling it for all mappings or for the selected mapping?

**Comment by igarashitm** [comment]
I would say it's only for selected mapping, but once it's enabled for that mapping, it needs to stay enabled so that the expression automatically appear when mapping is selected.

**Comment by pleacu** [comment]
Okay - that does appear more convenient for the user - I can't use my html trigger though - will withdraw this PR.

**Pull request closed without merging**
