### PR TITLE
DataSourceMetadata: change isSource getter and setter names fixes #2722

### LINKED ISSUE #2722: DataSourceMetadata: isSource parameter name problematic while reflection
For `camel-quarkus `project, we need to register for reflection all the classes used to serialize/deserialize data on runtime.
To have better performance, we register methods or fields. Since the fields are not public, I registred only methods.
I had a problem with the `DataSourceMetadata` class, because of the name of property is `isSource` does not match with getter/setter names. 
So for this class we need to register both methods and fields, to include the `@JsonProperty("isSource")`.

### PR DESCRIPTION
**Pull request by zbendhiba**
Fixes: #2722

### CODE REVIEW

**Review by igarashitm — APPROVED** [review]

**Comment by igarashitm** [comment]
Oops forgot to ask - can you add `fix:` prefix to the commit message?
https://github.com/atlasmap/atlasmap/wiki/AtlasMap-Developer-Memo#examples

Also adding a second line `Fixes: #2722` would automatically close the issue when it's merged.

**Comment by zbendhiba** [comment]
@igarashitm is the commit message  ok now ?

**Comment by igarashitm** [comment]
:+1:

**Comment by zbendhiba** [comment]
Thanks @igarashitm

**Pull request merged**
