### PR TITLE
fix: date converter support, boolean converter fix, non-primative con…

### PR DESCRIPTION
**Pull request by rohanmars**
…verter support

### CODE REVIEW

**Comment by igarashitm** [comment]
I thought we talked about that introducing `format` thing is too complex for the TypeConverter? At least can you file an another issue and describe what is it going to achieve? And like I said, I don't think we want to merge it before GA, while fixing #6 bug is still important.

BTW I guess DateConverter is eventually blocked by the #205 right? it's not gonna be triggered until #205 is addressed ...

**Comment by rohanmars** [comment]
Talking with @mattrpav  he agreed that support a format attribute is essential to date converter support. I think we need to lay out the case for it a bit clearer.

I don't think this PR or #6 is blocked by #205. Probably the other way around. The important change, IMHO, of this PR is that it introduces general non primitive type conversion support. Prior, the converters where hard coded. I changed this now to be a dynamic map of methods, keyed by source and target java types. So simply declaring an converter (via annotation) will cause it to be picked up. Which is necessary for the number conversion to. Then at run time these are dynamically invoked upon. 

How FieldTypes map to java (internal) objects is a separate question. One which I struggled with and is not full addressed in this PR. However, for the java to java use case this is okay now. The issues are more on the xml/json side I think, specifically when type is determined in the reader.

I think this PR will be necessary for #205.

**Comment by mattrpav** [comment]
@igarashitm I believe it is essential for supporting date and time formats in non-Java document types (Json, xml, etc). 

When parsing for input or writing for output a date format expression is going to be required, since the data is effectively “just a string” in both xml and Json. 

We’d be happy to hop on a call and discuss further as well

**Comment by igarashitm** [comment]
I meant,

> support a format attribute is essential to date converter support. I think we need to lay out the case for it a bit clearer.

I want to separate this one from #6 before discuss. Too bigger topic to inline within #6 bug fix. Note that we don't yet support `format` property in the JSON schema, which is required to be taken into account for date/time format handling.

> I don't think this PR or #6 is blocked by #205. Probably the other way around. The important change, IMHO, of this PR is that it introduces general non primitive type conversion support. Prior, the converters where hard coded. I changed this now to be a dynamic map of methods, keyed by source and target java types. So simply declaring an converter (via annotation) will cause it to be picked up. Which is necessary for the number conversion to. Then at run time these are dynamically invoked upon.

I think this is the one we expect for #6.

BTW I meant *DateConverter* is blocked by the #205, so it can't be utilized from the mapping generated via UI, unless #205 is addressed.

**Comment by igarashitm** [comment]
We might not have introduced date/time related atlasmap primitives even...

**Comment by igarashitm** [comment]
Also note that the format thing involves UX design, which makes it even larger. I don't like introduce runtime only thing at this stage.

**Comment by mattrpav** [comment]
@igarashitm given the timing, may I suggest that a ticket is created to address requested changes from this approach instead?  This set of changes is working and addresses the original requirements. If there is a desire to change direction, I believe it would be more efficient to address in a new issue vs rework what’s here. Also, redoing this work will take away from the requested component efforts. 

Be happy to hop on a call to discuss.

**Comment by igarashitm** [comment]
@mattrpav are you saying that you guys can even address the UXD and UI code as well for the format thing?

**Comment by mattrpav** [comment]
@igarashitm. No, I’m suggesting that supporting this in the runtime should have no impact to the UI. If the decision is to not support dates and times in Json and Xml for GA, no further dev should be needed. 

If the desire is to support dates and times for xml and Json for GA, than the UI would need to be updated anyway.

**Comment by igarashitm** [comment]
That's exactly why I want to have a separate thread, as it doesn't complete by itself

**Comment by rohanmars** [comment]
@igarashitm question: do you agree with the notion of a format attribute on an input/output field or not?

**Comment by igarashitm** [comment]
I'm not sure at this moment, and I do want to avoid introducing configuration into TypeConverter as far as we can. Mainly it introduces complexity in the UI. For me the date/time format thing can be addressed with the source side field action. Adding it in UI doesn't look so hard. But I don't yet know which is better eventually.

**Comment by igarashitm** [comment]
Just to make sure, I'm not saying this PR introduces complexity in the UI, because it hasn't addressed UI thing. But this definitely requires UI work which introduces complexity.

**Comment by rohanmars** [comment]
I'm not convinced that the field action approach will be sufficient. Specifically as the readers directly call the convertType method, thus supporting unmarshaling structured string values into specific types. I view the format attribute as a marshalling/unmarshalling hint. Interestingly enough, the writers should probably be extended to use the conversion service convertType method similar to the readers.

**Comment by igarashitm** [comment]
Do you have an example? Assuming Java-Java mapping, Do you mean having date/time format String field with `FieldType.DATE_TIME_TZ`? IMO that shouldn't happen. It should be `FieldType.STRING`, then source side field action would be `sourceType=FieldType.STRING` and `targetType=FieldType.DATE_TIME_TZ`. Then mapping to target field type `FieldType.DATE_TIME_TZ` doesn't require any converter. Java inspection never adds `FieldType.DATE_TIME_TZ` on a String field.

**Comment by igarashitm** [comment]
As per recent discussion we're going to merge this - @rohanmars can you rebase on top of upstream master?

**Comment by rohanmars** [comment]
Fixes #6 
Fixes #51

**Pull request merged**
