### PR TITLE
chore: Collect UI test coverage report and upload to CircleCI

### PR DESCRIPTION
**Pull request by igarashitm**
Fixes: #2075

### CODE REVIEW

**Comment by igarashitm** [comment]
It could be found in CircleCI build artifacts, but it might be better to publish upstream master results as a part of developer guide as well. I'll try that.

**Comment by igarashitm** [comment]
ugh now even `@atlasmap/atlasmap` test fails with exit code 137... and adding `--runInBand` causes this one - https://github.com/jsdom/jsdom/issues/2961

**Comment by igarashitm** [comment]
@riccardo-forina @gashcrumb it seems this `globalThis` not defined issue in JSDOM only happens with node v10
https://stackoverflow.com/questions/60976511/globalthis-underfined-for-jest-test-cases

Do you guys see any problem if we switch to node v12?

**Comment by riccardo-forina** [comment]
I guess it’s worth a shot. I’m syndesis we are stuck with v10 for reasons I haven’t investigated yet

**Comment by igarashitm** [comment]
No problem with node v12 for local build, fingers crossed...

**Comment by igarashitm** [comment]
I'll continue on #2098 for dev guide migration

**Pull request merged**
