### PR TITLE
[ENTESB-22698] Upgrade to Spring Framework 5.3.32

### PR DESCRIPTION
**Pull request by grgrzybek**
Fixes: #

### CODE REVIEW

**Comment by grgrzybek** [comment]
Should be a minor change. No rush @igarashitm ;)

**Comment by grgrzybek** [comment]
One of the failures is:
```
Could not extract archive: '/Users/runner/.m2/repository/com/github/eirslett/node/14.17.3/node-14.17.3-darwin-x64.tar.gz': EOFException
```
definitely not Spring Framework related ;)

**Review by igarashitm — APPROVED** [review]
Thx :+1: 
Yes we can ignore that macos error on extracting node binary, as it at least passes for ubuntu.

**Comment by igarashitm** [comment]
Merging - windows/java8 passed, windows/java11 is stuck at download but must be unrelated.

**Pull request merged**
