### PR TITLE
fix: Correct CSV dialog.

### PR DESCRIPTION
**Pull request by pleacu**
Fixes: #2746

### CODE REVIEW

**Comment by pleacu** [comment]
> Can you add story and unit test?

I don't think so - I didn't add anything structural - it's all visual.  I could create a new issue to walk through all of the CSV params and verify them.

**Comment by igarashitm** [comment]
There already is the story here, unit test could be added - https://github.com/atlasmap/atlasmap/blob/master/ui/packages/atlasmap/src/UI/dialogs/ParametersDialog.stories.tsx

**Comment by pleacu** [comment]
@igarashitm - pls re-review when you get a chance :)

**Comment by igarashitm** [comment]
The story looks good, how about the unit test?

**Comment by pleacu** [comment]
> The story looks good, how about the unit test?

Since there's no spec.ts yet for any dialog I was going to add that as a separate issue.

**Pull request merged**
