### PR TITLE
WIP: Angular deps upgraded incuding CLI

### PR DESCRIPTION
**Pull request by deeleman**
## WIP: PLEASE DO NOT MERGE

This PR has been submitted for review purposes and will be merged along with the changes required for https://github.com/syndesisio/syndesis/issues/424

Otherwise we would wind up publishing raw TypeScript files into npm that might trigger errors on clients importing this dependency on Angular versions prior to v5.

### CODE REVIEW

**Comment by igarashitm** [comment]
Hi @deeleman ,
Is it required to move tslint.json into ui directory? reason I moved it from ui directory to root was to let Codacy find that file. Also in the future we'll share it with atlasmap/app as well.

**Comment by igarashitm** [comment]
And one question, which is going to be a test report directory? circleci build is collecting ui/junit/* files, so it needs to be adjusted.
https://github.com/atlasmap/atlasmap/blob/b1db3f7a854c3b6bd88fec7ba4e88e539dcb9336/.circleci/config.yml#L63

**Comment by igarashitm** [comment]
Other than that LGTM! @gashcrumb , can you also take a look?

**Comment by deeleman** [comment]
@igarashitm
> Is it required to move tslint.json into ui directory? reason I moved it from ui directory to root was to let Codacy find that file.

Aww, was not aware of the Codacity setup until I saw it at the GiHub output. I've restored the file in its original location and updated the paths accordingly. In regards of `atlasmap/app`. In any event, I believe we should not take code directions in one way or another for projects that do not exist yet IMHO. 

> And one question, which is going to be a test report directory? circleci build is collecting ui/junit/* files, so it needs to be adjusted. 

Problem is that all the frontend tests are either broken or just empty, so there's not much to collect I'm afraid. In any event I've added a JUnit reporter in the Karma config so the UI application will dump test reports (reporting rubbish, basically) in an automatically generated `/ui/junit` folder upon running `yarn test`. This way we can leave the .circleci config as is.

Hopefully this helps. ;)

**Comment by igarashitm** [comment]
Thanks @deeleman !
Yeah those *.spec.ts are just scaffold I added, had no time to add real test cases. We should definitely enrich those (#100).

Surprisingly the coverage report says it already has 30% coverage, but I would say it's 0% right now.
https://81-106613119-gh.circle-artifacts.com/0/workspace/coverage/ui/lcov-report/index.html

**Comment by deeleman** [comment]
Closing this PR since it was submitted for code review purposes only and it is no longer relevant. A new Pr containing the upgrade to Angular 5 plus a proper npm packaging command will be submitted in parallel.

**Pull request closed without merging**
