### PR TITLE
fix: Correct extraneous concats in many-to-one preview mode.

### PR DESCRIPTION
**Pull request by pleacu**
Fixes: #2750

Also trigger mapping update on clearing values on preview disable.

### CODE REVIEW

**Comment by pleacu** [comment]
Yes - the `test('collection many-to-one deserialize/serialize', (done)` should cover it but I found a typo - one second...

**Comment by pleacu** [comment]
Corrected sample mappings typo - generated mapping info had to change

**Comment by igarashitm** [comment]
Can we get those json file pretty printed to be human readable? I think there're a couple of ways to compare JSON in structure, not necessarily strictly equal as a string literal.
https://stackoverflow.com/questions/26049303/how-to-compare-two-json-have-the-same-properties-without-order

**Comment by pleacu** [comment]
Good idea - I was wondering if there was a better way of diffing those JSON files.  Can we commit this first?  That way the new compare methodology can be a separate thing.

**Review by igarashitm — APPROVED** [review]

**Pull request merged**
