### PR TITLE
fix: Error when trying to concantenate two strings with expression

### PR DESCRIPTION
**Pull request by rkorytkowski**
Fixes: ENTESB-13912

### CODE REVIEW

**Comment by rkorytkowski** [comment]
@igarashitm I'm not sure, if we need to apply this fix at the ArithmeticExpression level or some more general fix is needed for all expressions. You may be better informed since it seems to be related to your changes in expressions.

**Comment by igarashitm** [comment]
@rkorytkowski I think this has a same root cause with ENTESB-13900 and ENTESB-13913, I'm working on it

**Comment by igarashitm** [comment]
#2112

**Comment by rkorytkowski** [comment]
Done in https://github.com/atlasmap/atlasmap/pull/2157

**Pull request closed without merging**
