### PR TITLE
fix: Support referencing complex elements in conditional expressions.

### PR DESCRIPTION
**Pull request by pleacu**
Fixes: #1604

### CODE REVIEW

**Comment by pleacu** [comment]
@igarashitm - No real React UI changes.  Please review all files.

**Comment by igarashitm** [comment]
Is it populating named `inputFieldGroup` with having children like this? runtime depends on those field structure to process expression.
https://github.com/atlasmap/atlasmap/blob/master/lib/itests/core/src/test/resources/mappings/atlasmapping-expression-filter-select-java.json#L19-L33

**Comment by pleacu** [comment]
> Is it populating named `inputFieldGroup` with having children like this? runtime depends on those field structure to process expression.
> https://github.com/atlasmap/atlasmap/blob/master/lib/itests/core/src/test/resources/mappings/atlasmapping-expression-filter-select-java.json#L19-L33

Yep - you're right - inputField need to be inputFieldGroup.  I'll work on that and resubmit - pls take a quick look at the rest.

**Comment by pleacu** [comment]
will resubmit - working on inputField -> inputFieldGroup.

**Pull request closed without merging**
