### PR TITLE
fix(ui): modals refactoring

### LINKED ISSUE #2045: Filter file types to *.adm and *.jar for import
When clicking on import, the tooltip is mentioning that only `*.adm` and `*.jar` are supported. The file picker is letting users to choose all kind of files.
In case, a not supported format is selected, there is no error, just nothing happens.

it will improve user experience to have the file picker to filter based on extensions.

### PR DESCRIPTION
**Pull request by riccardo-forina**
Drop react-file-picker, which is discontinued and buggy, to its
successor react-sage. Fixes #2045 #2046

Make modals normal React components, without useRef tricks.

Fixes dialogs rendering performance.

Ref ENTESB-13643 ENTESB-13644

### CODE REVIEW

**Comment by riccardo-forina** [comment]
@pleacu could you please verify if the custom class dialog is working ok? I'm not sure how to test it.

**Comment by riccardo-forina** [comment]
By the way, all dialogs have an associated story now. Eg. https://deploy-preview-2099--atlasmap.netlify.app/?path=/story/ui-dialogs--export-catalog-dialog

**Comment by igarashitm** [comment]
It seems e2e test is failing, the HTML is not found with xpath `//article[@aria-label='JSONSchemaSource'` after importing adm file.

**Comment by igarashitm** [comment]
https://github.com/atlasmap/atlasmap/blob/master/standalone/src/test/java/io/atlasmap/standalone/E2ETest.java#L98

**Comment by riccardo-forina** [comment]
Which makes sense, I removed them and forgot to add them back but a while ago. Why is it complaining now?

**Comment by igarashitm** [comment]
hmm not sure, this test is passing on both of CircleCI and local with current upstream master.

**Comment by igarashitm** [comment]
Is this PR adding a modal when importing adm file? then I guess it has to push OK button or something to proceed?

**Comment by riccardo-forina** [comment]
🤦‍♂️ you are right of course, I added a confirmation dialog after selecting the file to warn about the risk of losing non exported changes. That would explain it

**Comment by pleacu** [comment]
@riccardo-forina - custom class dialog looks a-ok

**Comment by riccardo-forina** [comment]
Cool thanks!

**Comment by igarashitm** [comment]
Adjusted e2e test

**Pull request merged**
